default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Assemble Build"
  lane :assemble_build do |options|
    properties = {
      "android.injected.signing.store.file" => "keystore.jks",
      "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
    } if @build_type == "Release"

    gradle(task: "assemble", build_type: @build_type, properties: properties)
  end

  desc "Assemble Test Application"
  lane :assemble_test_application do
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Assemble Build and Test Application"
  lane :assemble do
    assemble_build
    assemble_test_application
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_to_play_store do
    @build_type = "Release"
    assemble_build
    upload_to_play_store(track: 'internal')
  end
end
